baseURL = 'https://aratec.ca/'
languageCode = 'en-ca'
title = 'Aratec'
theme = 'cavani'
disableKinds = ['taxonomy']

[menu]
[[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
[[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = 2
[[menu.main]]
    name = 'Portfolio'
    pageRef = '/portfolio'
    weight = 3
[[menu.main]]
    name = 'Service'
    pageRef = '/service'
    weight = 4
[[menu.main]]
    name = 'Contact'
    pageRef = '/contact'
